### ISSUE TITLE
Issue importing Three.js

### ISSUE THREAD

**Issue by charles-hay** [aws-samples/amazon-sumerian-hosts#67] opened 2022-01-31 16:29 UTC
When I try to run the project I get the error 
```
Uncaught TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".
```

**Comment by rowedn** [comment] 2022-02-01 22:59
Hi charles-hay,

Can you provide us with some extra information for how you're building and running the project? Specifically we'd like to know:

- What operating system are you using?
- What version of NodeJS are you using?
- What commands did you run to build and serve the project?
- What project are you building?

If you could link us to whatever code you've written in your project that would be helpful as well.

**Comment by charles-hay** [comment] 2022-02-02 13:11
I was using Github Pages to run it when I changed the imports of `OrbitControls` and `GLTFLoader` to a local reference instead of a CDN it worked

**Comment by dcoder4** [comment] 2022-02-03 02:45
I get this same error when running the three.js demo out-of-the-box. Why? Dont get any issues with the babylon.js version.
@charles-hay when you say you changed the imports to local reference what did you actually do to make work?

**Comment by charles-hay** [comment] 2022-02-03 13:54
@dcoder4 so when you import `GLTFLoader` and `OrbitControls` it pulls from the CDN. Three.js doesn't like the import using a non-relative reference like `./, /, or ../` so I copied the raw code for those files from [here](https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/GLTFLoader.js) and [here](https://github.com/mrdoob/three.js/blob/master/examples/jsm/controls/OrbitControls.js) put it somewhere else in the repo and referenced it as a local reference. This is definitely not the most elegant solution but it works 🤷

**Comment by rowedn** [comment] 2022-02-03 21:04
I'm going to reopen this. I can reproduce this locally and I think this is an issue for everyone.

**Comment by charles-hay** [comment] 2022-02-03 21:22
@rowedn Did my suggestion not work or do you just want it fixed in the main repo?

**Comment by rowedn** [comment] 2022-02-03 21:23
@charles-hay We want it fixed in the main repo. Thanks for bringing this to our attention!

**Comment by charles-hay** [comment] 2022-02-03 21:33
@rowedn I just made that PR. idk if you want to use that implementation or not. tbh it's not the best

**Comment by rowedn** [comment] 2022-02-03 22:48
Looks like this was broken by a recent change to the version of three.js on the CDN: https://github.com/mrdoob/three.js/commit/eadd35e44c49eee5b3910cd2b761fbdfd05d6c67#diff-4728538b2d7d2a8298b8ac8ded9eafbe6e8515961e5b339e56cd3e47d40d3b49

We're working on a fix right now.

**Comment by charles-hay** [comment] 2022-02-07 15:08
So should I close my PR? #69

**Comment by brhook-aws** [comment] 2022-02-08 18:15
@charles-hay yes, you can close the PR. We may use it as a reference for the change we are making. Once the issue has been resolved and pushed, we'll close out this issue. Apologies for the inconvenience.

**Comment by charles-hay** [comment] 2022-02-09 18:12
@rahulss14 that would make sense since the update is what broke it. Big 🧠

**Comment by brhook-aws** [comment] 2022-02-10 23:32
We've merged in the change for the fix on this issue, which changes the CDN to a version one that should work. Please re-open the issue if you continue to experience issues.

**Closed by brhook-aws** 2022-02-10 23:32 UTC

**Comment by charles-hay** [comment] 2022-02-11 14:42
Thanks @brhook-aws
